title: CompSci Blogs
description: "My website"
owner_name: David Lee
github_username: DavidL0914
baseurl: "/student"
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
future: true
